---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: copy sshd_config to server
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart ssh

- name: restart sshd immediately to ensure port changes are activated
  service: name=sshd state=restarted

- name: ensure sshd is enabled
  service: name=sshd state=started enabled=yes
